# Generated by Django 4.0.4 on 2022-04-17 21:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('health_dept', models.IntegerField(blank=True, null=True)),
                ('police_dept', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
